# Generated by Django 3.0.7 on 2020-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=100)),
                ('years', models.CharField(max_length=20)),
            ],
        ),
    ]
