# Generated by Django 3.0.7 on 2020-06-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('years_from', models.IntegerField(blank=True)),
                ('years_to', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=25)),
                ('expert_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='years',
        ),
        migrations.AddField(
            model_name='job',
            name='years_from',
            field=models.IntegerField(blank=True, default=2008),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='years_to',
            field=models.IntegerField(blank=True, default=2009),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=25)),
                ('expert_percent', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.SkillCategory', to_field='category')),
            ],
        ),
    ]
