# Generated by Django 3.0.7 on 2020-06-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200606_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
