# Generated by Django 3.0.7 on 2020-06-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200606_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
