# Generated by Django 3.0.7 on 2020-06-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200606_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
