# Generated by Django 3.0.7 on 2020-06-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_auto_20200607_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('about_yourself', models.TextField()),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('profile_photo', models.ImageField(upload_to='images')),
                ('cover_photo_1', models.ImageField(upload_to='images')),
                ('cover_photo_2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_skill', models.CharField(max_length=100)),
            ],
        ),
    ]
