# Generated by Django 3.0.7 on 2020-06-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_aboutme_personalskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='last_name',
        ),
    ]
