# Generated by Django 3.0.7 on 2020-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20200608_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_1',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_2',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_photo',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
