# Generated by Django 3.0.7 on 2020-06-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_aboutme_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_1',
            field=models.FileField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_2',
            field=models.FileField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_photo',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
