# Generated by Django 3.0.7 on 2020-06-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20200611_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_1',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_2',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_photo',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(upload_to='images'),
        ),
    ]
