# Generated by Django 3.0.7 on 2020-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20200612_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='cover_photo_2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='profile_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
