# Generated by Django 3.0.7 on 2020-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_auto_20200612_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='favicon',
            field=models.ImageField(default='df', upload_to='images/'),
            preserve_default=False,
        ),
    ]
